config/routes.rb
Rails.application.routes.draw do
  # API
  namespace :api do
    resources :plates, only: [:show], param: :plate_number
  end
  resources :policies, only: [:index,:show,:new,:create,:destroy]
  resources :policies do
    resources :payments, only: [:new,:create]
  end

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
.container
  .row{style: 'padding-top: 100px;'}
    .col-md-6.col-md-offset-3
      .login-panel.panel.panel-default
        .panel-heading
          %h3.panel-title Iniciar Sesión
        .panel-body
          = form_for(:user, :url => session_path(:user),html: {role: "form", 'data-toggle': "validator"}) do |f|
            %fieldset
              .form-group
                = f.label :correo
                = f.email_field :email, class: 'form-control', required: true,'data-error': "Debe introducir su correo"
                .help-block.with-errors
              .form-group
                = f.label :clave
                = f.password_field :password, class: 'form-control', required: true,'data-error': "Debe introducir su clave"
                .help-block.with-errors
              .actions
                = f.submit 'Iniciar Sesión', class: "btn btn-success btn-block"
              = link_to "Regístrate", new_user_registration_path
              %br
              -# = link_to "¿Olvidó su clave?", new_password_path(:user)