config/routes.rb
Rails.application.routes.draw do
  # API
  namespace :api do
    resources :plates, only: [:show], param: :plate_number
  end
  resources :policies, only: [:index,:show,:new,:create,:destroy]
  resources :policies do
    resources :payments, only: [:new,:create]
  end

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :policy
  after_create_commit :update_policy_status
  validates :number_of_quotes, :credit_card_terminal, presence: true

  def update_policy_status
    # Lets simulate an aproved transaction from the payment service
    status = 'approved'
    case status
      when 'approved'
        # Set Aproved status
        self.policy.update_status("paid")
        # Send Email
        UserMailerJob.perform_later self.policy
      when 'error'
        self.policy.update_status('unpaid-error')
    end
    # Lets simulate a log in case of failur
    # Log.new_entry(error: 'Card Rejected', policy: self.policy.id, error_code: self.transaction.error_code)
  end

  private
    def payment_params
      params.require(:payment).permit(:policy_id, :number_of_quotes, :credit_card_terminal)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!

  # GET /payments/new
  def new
    @policy = Policy.find(params[:policy_id])
    if @policy.payment.nil?
      @payment = @policy.build_payment
    else
      redirect_to @policy
    end
  end

  # POST /payments
  # POST /payments.json
  def create
    # Verify if Policy have a payment
    @policy = Policy.find(params[:policy_id])
    unless @policy.payment.nil?
      redirect_to @policy
    end
    # Continue with creation
    @payment = Policy.find(params[:policy_id]).build_payment(payment_params)
    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment.policy, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment.policy }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:number_of_quotes, :credit_card_terminal)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.haml
= form_for [@policy,@payment], html: {role: "form", 'data-toggle': "validator"} do |f|
  %fieldset
    - if @payment.errors.any?
      #error_explanation
        %h2= "#{pluralize(@payment.errors.count, "error")} prohibited this payment from being saved:"
        %ul
          - @payment.errors.full_messages.each do |message|
            %li= message
    .form-group
      = f.label :número_de_cuotas
      = f.number_field :number_of_quotes, class: 'form-control', required: true, 'data-error': "Debe introducir el número de cuotas"
      .help-block.with-errors
    .form-group.hidden
      = f.text_field :credit_card_terminal, class: 'form-control'
    .form-group
      %label
        Nombre en la tarjeta
      %input.form-control#card-name{name: "card-holder-name", type: "text", required: true ,"data-error": "Debe introducir el Nombre de la tarjeta", "pattern": "^[a-zA-Z ]*$"}
      .help-block.with-errors
    .form-group
      %label
        Número de tarjeta
      %input.form-control#card-number{name: "card-number", type: "number", required: true ,'data-error': "Debe introducir el número de la tarjeta", "pattern": "^[0-9]*$","data-minlength": "13", maxlength:"16"}
      .help-block.with-errors
    .form-group
      %label
        Fecha de Expiración
      .form-group
        .row
          .col-xs-3
            %select#expiry-month.form-control.col-sm-2{:name => "expiry-month", required: true ,'data-error': "Debe seleccionar el mes de vencimiento"}
              %option
              %option{:value => "1"} Jan (01)
              %option{:value => "2"} Feb (02)
              %option{:value => "3"} Mar (03)
              %option{:value => "4"} Apr (04)
              %option{:value => "5"} May (05)
              %option{:value => "6"} June (06)
              %option{:value => "7"} July (07)
              %option{:value => "8"} Aug (08)
              %option{:value => "9"} Sep (09)
              %option{:value => "10"} Oct (10)
              %option{:value => "11"} Nov (11)
              %option{:value => "12"} Dec (12)
            .help-block.with-errors
          .col-xs-3
            %select.form-control#cc_year{:name => "expiry-year", required: true ,'data-error': "Debe seleccionar el año de vencimiento"}
              %option
              %option{:value => "2017"} 2017
              %option{:value => "2018"} 2018
              %option{:value => "2019"} 2019
              %option{:value => "2020"} 2020
              %option{:value => "2021"} 2021
              %option{:value => "2022"} 2022
              %option{:value => "2023"} 2023
              %option{:value => "2024"} 2024
              %option{:value => "2025"} 2025
              %option{:value => "2026"} 2026
              %option{:value => "2027"} 2027
            .help-block.with-errors
    .form-group
      %label
        CVV
      .form-group
        %input#cvv.form-control{name: "cvv",type: "password" ,placeholder: "Código de Seguridad", required: true ,'data-error': "Debe introducir el Numero CVV de la tarjeta","data-minlength": "3", maxlength:"4"}
        .help-block.with-errors
    .row
      .col-lg-12
        .actions
          .col-lg-6
            = f.submit 'Pagar', class: "btn btn-success btn-block", id:'pay-button'
          .col-lg-6
            = link_to 'Atrás', :back , class: "btn btn-default btn-block"

app/views/payments/index.html.haml
%h1 Listing payments

%table
  %thead
    %tr
      %th Policy
      %th User
      %th Number of quotes
      %th Credit card terminal
      %th
      %th
      %th

  %tbody
    - @payments.each do |payment|
      %tr
        %td= payment.policy
        %td= payment.user
        %td= payment.number_of_quotes
        %td= payment.credit_card_terminal
        %td= link_to 'Show', payment
        %td= link_to 'Edit', edit_payment_path(payment)
        %td= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' }

app/views/payments/new.html.haml
.container
  .row
    .panel.panel-default
      .panel-heading
        Nuevo Pago
      .panel-body
        = render 'form'