config/routes.rb
Rails.application.routes.draw do
  # API
  namespace :api do
    resources :plates, only: [:show], param: :plate_number
  end
  resources :policies, only: [:index,:show,:new,:create,:destroy]
  resources :policies do
    resources :payments, only: [:new,:create]
  end

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/policy.rb
class Policy < ApplicationRecord
  # SFC Cost
  SFC = 24589 # aprox based on document Tarifas_soat_2016C004-09.pdf
  RUNT = 1610 # RUNT based on document Tarifas_soat_2016C004-09.pdf
  MUERTES_Y_GASTOS_FUNERARIOS = '750 SMLDV' # based on document SOAT Prueba tecnica 2017.pdf
  GASTOS_MEDICOS = '800 SMLDV' # based on document SOAT Prueba tecnica 2017.pdf
  INCAPACIDAD_PERMANENTE = '180 SMLDV' # based on document SOAT Prueba tecnica 2017.pdf
  GASTOS_DE_TRANSPORTE = '10 SMLDV' # based on document SOAT Prueba tecnica 2017.pdf

  belongs_to :vehicle_type
  belongs_to :vehicle_sub_type
  belongs_to :user
  has_one :payment
  accepts_nested_attributes_for :payment
  after_create :policy_cost
  validates :vehicle_type_id,:vehicle_sub_type_id, :user_id, :plate, :age, presence: true
  validates :engine_cylinder, presence: true, if: :engine_cylinder_type?
  validates :number_of_passengers, presence: true, if: :number_of_passengers_type?
  validates :tons, presence: true, if: :tons_type?
  validates :plate, uniqueness: true

  def policy_cost
    self.issue_date = DateTime.now
    self.expiration_date = DateTime.now + 1.year
    self.commercial_rate = self.vehicle_sub_type.commercial_rate
    self.premium = self.vehicle_sub_type.commercial_rate * SFC
    self.fosyga = self.premium * 0.5
    self.runt = RUNT
    self.total = self.premium + self.fosyga + RUNT
    self.save
  end

  def update_status status
    self.policy_status = status
    self.save
  end

  def get_coverage
    {
      mgf: MUERTES_Y_GASTOS_FUNERARIOS,
      gm: GASTOS_MEDICOS,
      ip: INCAPACIDAD_PERMANENTE,
      gt: GASTOS_DE_TRANSPORTE,
    }
  end

  private
    def policy_params
      params.require(:policy).permit(:vehicle_type_id, :vehicle_sub_type_id, :user_id, :age, :number_of_passengers, :engine_cylinder, :tons, :plate, :issue_date, :expiration_date, :commercial_rate, :premium, :fosyga, :runt, :total, :policy_status)
    end

    def engine_cylinder_type?
      type = self.vehicle_type.name
      if type == "MOTOS" || type == "CAMPEROS Y CAMIONETAS" || type =="OFICIALES ESPECIALES" || type =="AUTOS FAMILIARES" || type =="VEHICULOS PARA SEIS O MAS PASAJEROS" || type == "AUTOS DE NEGOCIOS Y TAXIS"
        return true
      end
      return false
    end

    def number_of_passengers_type?
      self.vehicle_type.name == "SERVICIO PUBLICO INTERMUNICIPAL" ? true : false
    end

    def tons_type?
      self.vehicle_type.name == "CARGA O MIXTO" ? true : false
    end
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  before_action :set_policy, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /policies
  # GET /policies.json
  def index
    @policies = current_user.policies.all
  end

  # GET /policies/1
  # GET /policies/1.json
  def show
    respond_to do |format|
      format.html
      format.json
      format.pdf do
        render pdf: "show",:layout => 'policy_pdf'
      end
    end
  end

  # GET /policies/new
  def new
    @policy = current_user.policies.new
  end

  # POST /policies
  # POST /policies.json
  def create
    @policy = current_user.policies.new(policy_params)
    respond_to do |format|
      if @policy.save
        format.html { redirect_to @policy, notice: 'Policy was successfully created.' }
        format.json { render :show, status: :created, location: @policy }
      else
        format.html { render :new }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /policies/1
  # DELETE /policies/1.json
  def destroy
    @policy.destroy
    respond_to do |format|
      format.html { redirect_to policies_url, notice: 'Policy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_policy
      @policy = Policy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def policy_params
      params.require(:policy).permit(:vehicle_type_id, :vehicle_sub_type_id, :user_id, :age, :number_of_passengers, :engine_cylinder, :tons, :plate)
    end
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/views/policies/_form.html.haml
= form_for @policy, html: {role: "form", 'data-toggle': "validator"} do |f|
  %fieldset
    - if @policy.errors.any?
      #error_explanation
        %h2= "#{pluralize(@policy.errors.count, "error")} prohibited this policy from being saved:"
        %ul
          - @policy.errors.full_messages.each do |message|
            %li= message

    .form-group
      = f.label :tipo_de_vehículo
      %br
      = f.collection_select :vehicle_type_id, VehicleType.order(:name), :id, :name, {include_blank: true}, {required: true, class: 'form-control', 'data-error': "Debe seleccionar un tipo de vehículo"}
      .help-block.with-errors
    .form-group
      = f.label :sub_tipo_de_vehículo
      %br
      = f.grouped_collection_select :vehicle_sub_type_id, VehicleType.order(:name), :vehicle_sub_type, :name, :id, :description,{include_blank: true}, {class: 'form-control'}
    .form-group
      = f.label :edad
      = f.number_field :age, class: 'form-control',required: true,'data-error': "Debe introducir la edad de su vehículo"
      .help-block.with-errors
    .form-group
      = f.label :número_de_pasajeros
      = f.number_field :number_of_passengers, class: 'form-control', disabled: true
    .form-group
      = f.label :cilindrada
      = f.number_field :engine_cylinder, class: 'form-control', disabled: true
    .form-group
      = f.label :toneladas
      = f.number_field :tons, class: 'form-control', disabled: true
    .form-group
      = f.label :placa
      = f.text_field :plate, class: 'form-control',required: true,'data-error': "Debe introducir la placa de su vehículo"
      .help-block.with-errors
    .actions
      .row
        .col-lg-6
          = f.submit 'Generar', class: "btn btn-success btn-block"
        .col-lg-6
          = link_to 'Atrás', :back , class: "btn btn-default btn-block"

app/views/policies/index.html.haml
.container
  .row
    .panel.panel-default
      .panel-heading
        Mis pólizas
      - if @policies.count == 0
        .panel-body
          Aun no tienes pólizas, empieza creando una
          %button.btn.btn-success{"data-target" => "#plateModal", "data-toggle" => "modal", :type => "button"}
            Nueva Póliza
      -else
        .panel-body
          %table.table.table-bordered
            %thead
              %tr
                %th ID de la Póliza
                %th Placa
                %th Día de Emisión
                %th Día de Expiración
                %th Estado de la Póliza
                %th Prima Total
                %th Acciones

            %tbody
              - @policies.each do |policy|
                %tr
                  %td= policy.id
                  %td= policy.plate
                  %td= policy.issue_date
                  %td= policy.expiration_date
                  %td
                    - if policy.policy_status == 'paid'
                      Pagada
                    - else
                      No Pagada
                  %td= number_to_currency(policy.total, precision: 2)
                  %td
                    = link_to 'Ver Póliza', policy, class: "btn btn-default"
                    - unless policy.policy_status == 'paid'
                      = link_to 'Pagar Póliza', new_policy_payment_path(policy), class: "btn btn-success"
                    - if policy.policy_status == 'unpaid'
                      = link_to 'Borrar Póliza', policy, method: :delete, data: { confirm: '¿Está seguro que desea borrar la Póliza?' }, class: "btn btn-danger"
                    = link_to 'Descargar PDF', policy_path(policy, format: 'pdf'), class: "btn btn-primary", target: '_blanck'
          %button.btn.btn-success{"data-target" => "#plateModal", "data-toggle" => "modal", :type => "button"}
            Nueva Póliza

-# Modal
#plateModal.modal.fade{:role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4.modal-title Verificar Placa del Vehiculo
      .modal-body
        .form-group
          %label
            Número de Placa
          %input.form-control#plate-number{name: "plate-number", type: "text", required: true ,'data-error': "Debe introducir la placa"}
          .help-block.with-errors
        %p.validate-error.hidden
          La placa ya se encuentra registrada en el sistema, por favor verifique
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Cerrar
        %button.btn.btn-primary#plate_validate_button{:type => "button"} Verificar
        = link_to 'Nueva Póliza', new_policy_path, class: 'btn btn-success disabled hidden', id: "new_policy_button"

app/views/policies/new.html.haml
.container
  .row
    .panel.panel-default
      .panel-heading
        Nueva Póliza
      .panel-body
        = render 'form'

app/views/policies/show.html.haml
.container
  .row
    .panel.panel-default
      .panel-heading
        %h2
          = "Detalles de la póliza: #{@policy.id}"
      .panel-body
        .row
          .col-xs-12.col-sm-6.col-md-6.col-lg-6
            %h3 Tipo de vehículo
          .col-xs-12.col-sm-6.col-md-6.col-lg-6
            %h3 Sub tipo de vehículo
        .row
          .col-xs-12.col-sm-6.col-md-6.col-lg-6
            = @policy.vehicle_type.name
          .col-xs-12.col-sm-6.col-md-6.col-lg-6
            = @policy.vehicle_sub_type.sub_type_description
        .row
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            %h3 Edad:
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            %h3 Número de Pasajeros:
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            %h3 Tipo de motor:
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            %h3 Toneladas:
        .row
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            = @policy.age
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            = @policy.number_of_passengers
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            = @policy.engine_cylinder
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            = @policy.tons
        .row
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            %h3 Placa:
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            %h3 Día de Emisión:
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            %h3 Día de Expiración:
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            %h3 Taza Comercial:
        .row
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            = @policy.plate
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            = @policy.issue_date
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            = @policy.expiration_date
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            = @policy.commercial_rate
        .row
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            %h3 Prima:
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            %h3 Fosyga:
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            %h3 Runt:
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            %h3 Total:
        .row
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            = number_to_currency(@policy.premium, precision: 2)
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            = number_to_currency(@policy.fosyga, precision: 2)
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            = @policy.runt
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            = number_to_currency(@policy.total, precision: 2)
        .row
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            %h3 Muertes y Gastos Funerarios:
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            %h3 Gastos Médicos:
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            %h3 Incapacidad Permanente:
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            %h3 Gastos de Transporte:
        .row
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            = @policy.get_coverage[:mgf]
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            = @policy.get_coverage[:gm]
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            = @policy.get_coverage[:ip]
          .col-xs-12.col-sm-6.col-md-3.col-lg-3
            = @policy.get_coverage[:gt]
        %br
        .row
          .col-xs-12.col-sm-6.col-md-12.col-lg-12
            = link_to 'Atrás', policies_path, class: "btn btn-default"
  .row
    .panel.panel-default
      .panel-heading
        %h2
          = "Detalles del Pago"
      .panel-body
        - if @policy.payment
          .row
            .col-xs-12.col-sm-6.col-md-3.col-lg-3
              %h3 Fecha de Pago:
            .col-xs-12.col-sm-6.col-md-3.col-lg-3
              %h3 Número de Cuotas:
            .col-xs-12.col-sm-6.col-md-3.col-lg-3
              %h3 Tarjeta de Crédito:
            .col-xs-12.col-sm-6.col-md-3.col-lg-3
              %h3 Total:
          .row
            .col-xs-12.col-sm-6.col-md-3.col-lg-3
              = @policy.payment.created_at
            .col-xs-12.col-sm-6.col-md-3.col-lg-3
              = @policy.payment.number_of_quotes
            .col-xs-12.col-sm-6.col-md-3.col-lg-3
              = "**** **** **** #{@policy.payment.credit_card_terminal}"
            .col-xs-12.col-sm-6.col-md-3.col-lg-3
              = number_to_currency(@policy.total, precision: 2)
          .row
            .col-xs-12.col-sm-6.col-md-3.col-lg-3
              = link_to 'Atrás', policies_path, class: "btn btn-default"
        - else
          %p
            Debe Pagar su Póliza, para hacerlo puede hacer click en el siguiente boton
            = link_to 'Pagar Póliza', new_policy_payment_path(@policy), class: "btn btn-success"
            = link_to 'Atrás', policies_path, class: "btn btn-default"

app/views/policies/show.pdf.erb
<div class="policy">
  <h1 style="text-align:center;">P&oacute;liza - SOAT</h1>
  <!-- Policy Information -->
  <table style="width: 100%;text-align: left;border: 1px solid black;">
    <h3>Datos de la P&oacute;liza</h3>
    <thead>
      <tr>
        <th style="padding-bottom: 15px;border: 1px solid black;">N&uacute;mero de P&oacute;liza</th>
        <th style="padding-bottom: 15px;border: 1px solid black;">Sub Tipo de veh&iacute;culo</th>
        <th style="padding-bottom: 15px;border: 1px solid black;">Sub Tipo de veh&iacute;culo</th>
        <th style="padding-bottom: 15px;border: 1px solid black;">Placa</th>
      </tr>
    </thead>
      <tbody>
        <tr>
          <td style="font-size: 15px"><%= @policy.id %></td>
          <td style="font-size: 15px"><%= @policy.vehicle_type.name %></td>
          <td style="font-size: 15px"><%= @policy.vehicle_sub_type.sub_type_description %></td>
          <td style="font-size: 15px"><%= @policy.plate %></td>
        </tr>
      </tbody>
      <thead>
        <tr>
          <th style="padding-bottom: 15px;;border: 1px solid black;">Edad</th>
          <th style="padding-bottom: 15px;;border: 1px solid black;">N&uacute;mero de Pasajeros</th>
          <th style="padding-bottom: 15px;;border: 1px solid black;">Tipo de Motor</th>
          <th style="padding-bottom: 15px;;border: 1px solid black;">Toneladas</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="font-size: 15px"><%= @policy.age %></td>
          <td style="font-size: 15px"><%= @policy.number_of_passengers %></td>
          <td style="font-size: 15px"><%= @policy.engine_cylinder %></td>
          <td style="font-size: 15px"><%= @policy.tons %></td>
        </tr>
      </tbody>
      <thead>
        <tr>
          <th style="padding-bottom: 15px;;border: 1px solid black;">D&iacute;a de Emisi&oacute;n</th>
          <th style="padding-bottom: 15px;;border: 1px solid black;">D&iacute;a de Expiraci&oacute;n</th>
          <th style="padding-bottom: 15px;;border: 1px solid black;">Taza Comercial</th>
          <th style="padding-bottom: 15px;;border: 1px solid black;">Total</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="font-size: 15px"><%= @policy.issue_date %></td>
          <td style="font-size: 15px"><%= @policy.expiration_date %></td>
          <td style="font-size: 15px"><%= @policy.commercial_rate %></td>
          <td style="font-size: 15px"><%=number_to_currency(@policy.premium, precision: 2)%></td>
        </tr>
      </tbody>
      <thead>
        <tr>
          <th style="padding-bottom: 15px;;border: 1px solid black;">Muertes y Gastos Funerarios</th>
          <th style="padding-bottom: 15px;;border: 1px solid black;">Gastos M&eacute;dicos</th>
          <th style="padding-bottom: 15px;;border: 1px solid black;">Incapacidad Permanente</th>
          <th style="padding-bottom: 15px;;border: 1px solid black;">Gastos de Transporte</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="font-size: 15px"><%= @policy.get_coverage[:mgf] %></td>
          <td style="font-size: 15px"><%= @policy.get_coverage[:gm] %></td>
          <td style="font-size: 15px"><%= @policy.get_coverage[:ip] %></td>
          <td style="font-size: 15px"><%= @policy.get_coverage[:gt]%></td>
        </tr>
      </tbody>
  </table>

  <!-- User Information -->
  <table style="width: 100%;text-align: left;border: 1px solid black;">
    <h3>Datos del Tomador</h3>
    <thead>
      <tr>
        <th style="padding-bottom: 15px;border: 1px solid black;">Nombre</th>
        <th style="padding-bottom: 15px;border: 1px solid black;">Apellido</th>
        <th style="padding-bottom: 15px;border: 1px solid black;">Correo</th>
      </tr>
    </thead>
      <tbody>
        <tr>
          <td style="font-size: 15px"><%= @policy.user.name %></td>
          <td style="font-size: 15px"><%= @policy.user.last_name %></td>
          <td style="font-size: 15px"><%= @policy.user.email %></td>
        </tr>
      </tbody>
      <thead>
        <tr>
          <th style="padding-bottom: 15px;;border: 1px solid black;">N&uacute;mero de Tel&eacute;fono</th>
          <th style="padding-bottom: 15px;;border: 1px solid black;">Tipo de Documento</th>
          <th style="padding-bottom: 15px;;border: 1px solid black;">Documento</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="font-size: 15px"><%= @policy.user.phone %></td>
          <td style="font-size: 15px"><%= @policy.user.document_type %></td>
          <td style="font-size: 15px"><%= @policy.user.document_id %></td>
        </tr>
      </tbody>
  </table>

  <!-- Payment Information -->
  <% if @policy.payment %>
    <table style="width: 100%;text-align: left;border: 1px solid black;">
      <h3>Datos del Pago</h3>
      <thead>
        <tr>
          <th style="padding-bottom: 15px;border: 1px solid black;">Fecha de Pago</th>
          <th style="padding-bottom: 15px;border: 1px solid black;">N&uacute;mero de Cuotas</th>
          <th style="padding-bottom: 15px;border: 1px solid black;">Tarjeta de Cr&eacute;dito</th>
        </tr>
      </thead>
        <tbody>
          <tr>
            <td style="font-size: 15px"><%= @policy.payment.created_at %></td>
            <td style="font-size: 15px"><%= @policy.payment.number_of_quotes %></td>
            <td style="font-size: 15px"><%= "**** **** **** #{@policy.payment.credit_card_terminal}" %></td>
          </tr>
        </tbody>
        <thead>
          <tr>
            <th style="padding-bottom: 15px;;border: 1px solid black;">Prima</th>
            <th style="padding-bottom: 15px;;border: 1px solid black;">Fosyga</th>
            <th style="padding-bottom: 15px;;border: 1px solid black;">Total</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td style="font-size: 15px"><%=number_to_currency(@policy.premium, precision: 2)%></td>
            <td style="font-size: 15px"><%= number_to_currency(@policy.fosyga, precision: 2) %></td>
            <td style="font-size: 15px"><%= number_to_currency(@policy.total, precision: 2) %></td>
          </tr>
        </tbody>
    </table>
  <% else %>
    <h2 style="text-align:center;">Debe pagar la P&oacute;liza</h2>
  <% end %>

</div>